timestamp_utc: '2026-01-26T10:00:00Z'
arguments:
  filepath: /proj/ie/proj/SMOKE/htran/Emission_Modeling_Platform/utils/smkplot/example_inputs/example_ff10.csv
  sector: test_ff10
  county_shapefile: /proj/ie/proj/staff/tranhuy/python/GIS/tl_2020_us_county_CONUS.gpkg
  griddesc: /proj/ie/proj/SMOKE/htran/Emission_Modeling_Platform/utils/smkplot/example_inputs/example_griddesc.txt
  gridname: 12LISTOS
  pltyp: county
  pollutant: NOX,VOC
  zoom_to_data: true
  cmap: viridis
  outdir: ./test_outputs/ff10
  export_csv: true
  run_mode: batch
