timestamp_utc: '2026-01-26T11:00:00Z'
arguments:
  filepath: example_inputs/example_ff10_point.csv
  sector: test_ff10_point_grid
  griddesc: example_inputs/example_griddesc.txt
  gridname: 12LISTOS
  pltyp: grid
  pollutant: NOX,VOC
  zoom_to_data: true
  outdir: test_outputs/ff10_point_grid
  export_csv: true
  run_mode: batch
